functionsDirectory = "/Users/radu.diaconescu/romania-energy-dashboard/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/radu.diaconescu/romania-energy-dashboard/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/radu.diaconescu/romania-energy-dashboard/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/sen-filter"
to = "/.netlify/functions/sen-filter"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]